### PR TITLE
Overhaul with Dual App Option

### PR DESCRIPTION
**Pull request by jasonmeurer**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jasonmeurer** [comment]
The json files should be removed.  I have moved to yaml.

**Review by jpeezus — APPROVED** [review]
Jason's changes approved

**Review by jpeezus — APPROVED** [review]
changes approved

**Review by jpeezus — APPROVED** [review]
changes approved

**Review by jpeezus — APPROVED** [review]
approved

**Review by jpeezus — APPROVED** [review]

**Pull request merged**
